config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcomes#home'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "/auth/google_oauth2" => "sessions#create_from_omniauth"

  # get "todos/search" => "todos#search"
  post "todos/search" => "todos#search"

  get "todos/:id/find" => "todos#ajax_find"

  post "todos/:id/add_image" => "todos#add_image", :as => 'todo_add_image'
  post "todos/:id/add_gif" => "todos#add_gif", :as => 'todo_add_gif'

  # resources :search, only: [:index]
  # resources :welcome
  # resources :users
  resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user

  def self.create_with_omniauth(auth_hash)
  	self.new(
  		provider: auth_hash['provider'],
  		uid: auth_hash['uid'],
  		token: auth_hash['credentials']['token']
  	)
  end

  def update_token
  	self.token = auth_hash['credentials']['token']
  	self.save
  end
end

app/models/todo.rb
class Todo < ApplicationRecord
	belongs_to :user
	include PgSearch
	pg_search_scope :search_name, :against => :title, :using => [:tsearch]
	mount_uploaders :images, ImageUploader

	def complete?
		@complete
	end

	def complete!
		@complete = true
	end
end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
	include BCrypt
	has_secure_password
	has_many :todos
	validates :email, uniqueness: true
	validates :name, :email, :password, presence: true
	validates :password, confirmation: { case_sensitive: true }

	def self.create_with_auth_and_hash(authentication, auth_hash)
		user = self.create!(
			name: auth_hash['info']['name'],
			email: auth_hash['info']['email'],
			password: SecureRandom.hex(10)
		)
		# user.authentications << authentication
		return user
	end

	def google_token
		x = self.authentications.find_by(provider: 'google_oauth2')
		return x.token unless x.nil?
	end
end

app/models/welcome.rb
class Welcome < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery
	
	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
	helper_method :current_user

	def authorize
		redirect_to '/login' unless current_user
	end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

	def index
		if params[:query].present?
			todos = Todo.search(params[:query])
		else
			@todos = Todo.all
		end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
skip_before_action :verify_authenticity_token

	def new
	end

	def create
		@user = User.find_by_email(params[:email])
		if @user && @user.authenticate(params[:password])
			session[:user_id] = @user.id
			redirect_to todos_path
		else
			flash[:failure] = 'Invalid password or email'
			redirect '/login'
		end
	end

	def create_from_omniauth
		auth_hash = request.env["omniauth.auth"]
		authentication = Authentication.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"]) ||  Authentication.create_with_omniauth(auth_hash)

		  # if: previously already logged in with OAuth
		  if authentication.user
		    user = authentication.user
		    authentication.update_token(auth_hash)
		    @next = root_url
		    @notice = "Signed in!"
		  # else: user logs in with OAuth for the first time
		  else
		    user = User.create_with_auth_and_hash(authentication, auth_hash)
		    # you are expected to have a path that leads to a page for editing user details
		    @next = root_url
		    @notice = "User created. Please confirm or edit details"
		  end
		  session[:user_id] = user.id
		  redirect_to @next, :notice => @notice
	end

	def destroy
		session[:user_id] = nil
		redirect_to '/login'
	end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
	before_action :authorize

	def index
		@todos = Todo.where(user_id: current_user.id)
		# render :partial => "todo.html.erb", :collection => Todo.where(user_id: current_user.id)
		@todo = Todo.new
	end

	def new	
		@todo = Todo.new
	end

	def show
		@todo = Todo.find(params[:id])
	end

	def ajax_find
		@todo = Todo.find(params[:id])
		# This is new AJAX
		# respond_to do |format|
		# 		format.js
		# 		format.html
		# end

		#This is traditional AJAX
		render json: @todo
	end

	def create
		@todo = current_user.todos.new(todo_params)

		if @todo.save
			redirect_to todos_path
		else
			redirect_to new_todo_path
		end
	end

	def edit
		@todo = Todo.find(params[:id])
		render 'todos/edit'
	end

	def update
		todo = Todo.find(params[:id])
		todo.update(todo_params)
		redirect_to todos_path
	end

	def add_image
		@todo = Todo.find(params['id'])
		@todo.update(image_params)
		redirect_to todos_path
	end

	def add_gif
		@todo = Todo.find(params['id'])
		# @todo.images << params['gif']
		@todo.update(remote_images_urls: [params['gif']])
		render json: @todo
	end

	def destroy
		todo = Todo.find(params[:id])
		todo.destroy
		redirect_to todos_path
	end

	def search
		if params[:query].present?
			@todos = Todo.search_name(params[:query])
			@todo = Todo.new
			respond_to do |format|
				format.js
				format.html
			end
		else
			@todos = Todo.where(user_id: current_user.id )
		end
	end

	private
	def todo_params
		params.require(:todo).permit(:title, :due_date, :priority)
	end

	def image_params
		params.require(:todo).permit(:id, {images: []})
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
	  @user = User.new(user_params)
	  if @user.save
	  	flash[:success] = 'Welcome to Todoist!'
	  	session[:user_id] = @user.id
	  	redirect_to todos_path
	  else
	  	flash[:failure] = 'Invalid email or password.'
	  	redirect_to '/signup'
	  end
	end

	def login
	  @user = User.find_by_email(params[:email])
	  if @user.password == params[:password]
	    give_token
	  else
	    redirect_to todos_path
	  end
	end

	private
	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  before_action :set_welcome, only: [:show, :edit, :update, :destroy]

  # GET /welcomes
  # GET /welcomes.json

  def home
  end
  
  def index
  end

  # GET /welcomes/1
  # GET /welcomes/1.json
  def show
  end

  # GET /welcomes/new
  def new
    @welcome = Welcome.new
  end

  # GET /welcomes/1/edit
  def edit
  end

  # POST /welcomes
  # POST /welcomes.json
  def create
    @welcome = Welcome.new(welcome_params)

    respond_to do |format|
      if @welcome.save
        format.html { redirect_to @welcome, notice: 'Welcome was successfully created.' }
        format.json { render :show, status: :created, location: @welcome }
      else
        format.html { render :new }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /welcomes/1
  # PATCH/PUT /welcomes/1.json
  def update
    respond_to do |format|
      if @welcome.update(welcome_params)
        format.html { redirect_to @welcome, notice: 'Welcome was successfully updated.' }
        format.json { render :show, status: :ok, location: @welcome }
      else
        format.html { render :edit }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /welcomes/1
  # DELETE /welcomes/1.json
  def destroy
    @welcome.destroy
    respond_to do |format|
      format.html { redirect_to welcomes_url, notice: 'Welcome was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_welcome
      @welcome = Welcome.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def welcome_params
      params.fetch(:welcome, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/todo_helper.rb
module TodoHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoistClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.3/semantic.min.css">
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"
  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
  crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.3/semantic.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
    Signed in as <%= current_user.name %> | <%= link_to 'Logout', '/logout' %> | <%= link_to 'Your Todos', todos_path %>
    <% else %>
      <%= link_to 'Login', '/login' %> | <%= link_to 'Sign up', '/signup' %> | <%= link_to "Sign in with Google", "/auth/google_oauth2" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_for @todo, url: {action: "create"},  html: {class: "ui form"} do |f|%>
	<%= f.text_field :title %>
	<%= f.datetime_select :due_date %>
	<%= f.select :priority, (1...4) %>
	<%= f.submit 'Add Task' %>
<% end %>

app/views/todos/_todo.html.erb
<% if @todos %>
<% @todos.each do |todo| %>
<div class="item">
	<i class="circle outline icon"></i>
	<div class="content">
	  <span><p style="line-height: 1em; */" id="todo<%= todo.id %>"><%= todo.title %> | <%= todo.due_date.strftime('%b %d %H:%M') %> | <%= link_to 'Edit', edit_todo_path(todo.id) %> | <%= link_to 'Delete', todo_path(todo.id), :method => :delete %></p></span>
	  <!-- <div class="description">Updated 10 mins ago</div> -->
	</div>
</div>
<% end %>
<% end %>

app/views/todos/add_image.js.erb
<% if remotipart_submitted? %>
  alert('submitted via remotipart')
<% else %>
  alert('submitted via native jquery-ujs')
<% end %>

app/views/todos/edit.html.erb
<%= form_for @todo, url: {action: "update"} do |f|%>
	<%= f.text_field :title %></br>
	<%= f.datetime_select :due_date %></br>
	<%= f.select :priority, (1...5) %></br>
	<%= f.submit 'Save' %>
<% end %>

app/views/todos/index.html.erb
<div id=topbar>
	<div class="ui six column">
		<div class="column">
			<img src="https://vignette.wikia.nocookie.net/logopedia/images/1/1b/Todoist.svg/revision/latest?cb=20151024153919" id="logo">
		</div>
	</div>
</div>



<div class="ui grid">
	<div class="six wide column">
		<i class="large inbox icon"></i>Inbox
		<div class="ui search">
		  <div class="ui icon input">
		    <%= form_for @todo, :remote => true, url:{controller: 'todos', action: 'search'} do |f| %>
		    <%= f.text_field :title, :name => "query", :id => 'query', :placeholder => "Quick Find", :class => 'prompt' %>
		    <i class="search icon"></i>
		    <%= f.submit "Search" , :id => "search" %>
		    <% end %>
		  </div>
		  <div class="results"></div>
		</div>
	</div>
	<div class="ten wide column">
		<div class="ui relaxed divided list" id="todo-list">
		<% if @todos %>
		<% @todos.each do |todo| %>
		<div class="item">
			<i class="circle outline icon"></i>
			<div class="content">
			  <span><p style="line-height: 1em;" id="<%= todo.id %>"><%= link_to todo_path(todo.id) do %> <%= todo.title %> <% end %>| <%= todo.due_date.strftime('%b %d %H:%M') %> | <button id="modal-show<%=todo.id%>"><i class="comment outline icon modal" ></i></button> | <%= link_to 'Edit', edit_todo_path(todo.id) %> | <%= link_to 'Delete', todo_path(todo.id), :method => :delete %></p></span>
			  
			  <!-- <div class="description">Updated 10 mins ago</div> -->
			</div>
		</div>
		<% end %>
		<% end %>
		</div>
		<!-- I'll be making here AJAX later -->
		<i class="large plus icon"></i> <%= link_to 'Add Task', new_todo_path %> 
	</div>
</div>
<% if @todos %>
<% @todos.each do |todo| %>
<div class="ui modal" id="modal<%=todo.id%>">
  <i class="close icon" id="close-icon-in-add-gif<%=todo.id%>"></i>
  <div class="header">
  	<h3 id="modal-title<%=todo.id%>"></h3>
  	<p id="modal-due<%=todo.id%>"></p>
  </div>
  <div class="content">
    <div class="description" id="description-add-gif<%=todo.id%>">
    	 <% if !todo.images.empty? %>
    	 	<% todo.images.each do |image| %>
    	 		<%= image_tag(image.url, :class => "ui medium rounded image") %>
    	 	<% end %>
    	 <% end %>
  </div>
  <div class="actions">
	<hr>
    <div class="ui icon button" id="add-gif<%=todo.id%>">
      <i class="smile outline icon"></i>
    </div>
    <%= form_for todo, url: todo_add_image_path(todo.id), html: {:class => "image-form", :id => "form#{todo.id}"}, method: :post do |f| %>
	    <label for="file-input" class="ui icon button">
	  		<i class="images outline icon"></i>
		</label>
    	<%= f.file_field :images, multiple: true, id:"file-input" %>
    	<%= f.submit %>
    <% end %>
      <div class="ui search gif" id="hidden-gif-search-add-gif<%=todo.id%>" style="display: none;">
		  <div class="ui icon input">
		    <input class="prompt" type="text" placeholder="Type something crazy...">
		    <i class="search icon"></i>
		  </div>
		  <div class="results"></div>
	  </div>
  </div>
</div>
<% end %>
<% end %>

<style type="text/css">
	#file-input {
		display: none;
	}

	.image-form {
		display: inline;
	}

</style>

app/views/todos/new.html.erb
<%= form_for @todo, url: {action: "create"} do |f|%>
	Title: <%= f.text_field :title %></br>
	Due Date: <%= f.datetime_select :due_date %></br>
	Priority: <%= f.select :priority, (1...5) %></br>
	<%= f.submit 'Add Task' %>
<% end %>

app/views/todos/search.js.erb
<% content = @todos.map do |todo| %>
	<% "<div class='item'> <i class='circle outline icon'></i> <div class='content'> <span><p style='line-height: 1em;' id='todo#{todo.id}'>  #{link_to "#{todo.title}", todo_path(todo.id) } | #{todo.due_date.strftime('%b %d %H:%M')} | <button id='modal-show#{todo.id}'><i class='comment outline icon modal' ></i></button> | #{link_to 'Edit', edit_todo_path(todo.id)} |  #{link_to 'Delete', todo_path(todo.id), :method => :delete} </p></span></div> </div>" %>
<% end %>
var todos = <%= raw content.join().to_json %>
$('#todo-list').find('div').remove();
$('#todo-list').html(todos);

app/views/todos/show.html.erb
<div class="ui container">
Title: <%= @todo.title %>
	
</div>

app/views/users/new.html.erb
<h1>Please sign up.</h1>

<%= form_for :user, url: '/users' do |f| %>
	Name: <%= f.text_field :name %></br>
	Email: <%= f.text_field :email%></br>
	Password: <%= f.password_field :password %></br>
	Password Confirmation: <%= f.password_field :password_confirmation %></br>
	<%= f.submit "Submit" %>

<% end %>

app/views/welcomes/edit.html.erb
<h1>Editing Welcome</h1>

<%= render 'form', welcome: @welcome %>

<%= link_to 'Show', @welcome %> |
<%= link_to 'Back', welcomes_path %>

app/views/welcomes/home.html.erb
<h1>Welcome to Todoist clone!</h1>

app/views/welcomes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Welcomes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @welcomes.each do |welcome| %>
      <tr>
        <td><%= link_to 'Show', welcome %></td>
        <td><%= link_to 'Edit', edit_welcome_path(welcome) %></td>
        <td><%= link_to 'Destroy', welcome, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Welcome', new_welcome_path %>

app/views/welcomes/new.html.erb
<h1>New Welcome</h1>

<%= render 'form', welcome: @welcome %>

<%= link_to 'Back', welcomes_path %>

app/views/welcomes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_welcome_path(@welcome) %> |
<%= link_to 'Back', welcomes_path %>